### ISSUE TITLE
CUADRO COMPARATIVO DE TEXTOS

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Jaczibeth#1]
JACZIBETH CRUZ RAMIREZ 1BS
[LOS TIPO DE TEXTOS_JACZI1BS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Jaczibeth/files/9637752/LOS.TIPO.DE.TEXTOS_JACZI1BS.pdf)
[LOSTIPO DE TEXTOS_JACZI1BS.docx](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Jaczibeth/files/9637753/LOSTIPO.DE.TEXTOS_JACZI1BS.docx)

**Comment by 11042002** [comment]
Tu calificación es de: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
